from skillshare import skillshare

cookie = """
[
    {
        "domain": ".skillshare.com",
        "expirationDate": 1680243527,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_uetvid",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "044ee67090fe11ec8e9adbdb9dada638"
    },
    {
        "domain": "www.skillshare.com",
        "hostOnly": true,
        "httpOnly": false,
        "name": "YII_CSRF_TOKEN",
        "path": "/",
        "sameSite": "lax",
        "secure": false,
        "session": true,
        "storeId": null,
        "value": "S2EwQ1dHZmt2aGh3cWRWZjJBTng1Zk01a25DMWlzWkgv2eX_u_BkzUGiE59s2n4wmi-qX8pU16K0d6IUB90IAg%3D%3D"
    },
    {
        "domain": ".skillshare.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "IR_gbd",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": true,
        "storeId": null,
        "value": "skillshare.com"
    },
    {
        "domain": ".skillshare.com",
        "expirationDate": 1646548119,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__utmt",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "1"
    },
    {
        "domain": ".skillshare.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "__utmc",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": true,
        "storeId": null,
        "value": "99704988"
    },
    {
        "domain": ".skillshare.com",
        "expirationDate": 1679404820,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_sctr",
        "path": "/",
        "sameSite": "lax",
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "1|1645209000000"
    },
    {
        "domain": ".www.skillshare.com",
        "expirationDate": 1678083529,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__stripe_mid",
        "path": "/",
        "sameSite": "strict",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "bb1b947b-a2dc-45b3-8416-7d59fee4e83a0a6c48"
    },
    {
        "domain": ".skillshare.com",
        "expirationDate": 1646549327,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__utmb",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "99704988.2.10.1646547519"
    },
    {
        "domain": ".skillshare.com",
        "expirationDate": 1708755527,
        "hostOnly": false,
        "httpOnly": false,
        "name": "IR_PI",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "5346bf8f-9235-11ec-a792-697bbaeebf12%7C1646633927484"
    },
    {
        "domain": ".skillshare.com",
        "expirationDate": 1709619527,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__utma",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "99704988.1620411679.1645218121.1645721100.1646547519.5"
    },
    {
        "domain": ".www.skillshare.com",
        "expirationDate": 1646549329,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__stripe_sid",
        "path": "/",
        "sameSite": "strict",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "855f7fd9-db82-43a6-9709-51890dc15139408a96"
    },
    {
        "domain": ".skillshare.com",
        "expirationDate": 1771582243,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__ssid",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "0bc9d4b9ce3748822701d843608eb96"
    },
    {
        "domain": ".skillshare.com",
        "expirationDate": 1646549319.500208,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__cf_bm",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "O0OrZjflGAewfRESfZsGKXlSgouufqG7EUtOgWAjrt8-1646547518-0-AbNjwr504oXBsayky1OW/6GBgPPvQmlkU2zCgqiHGFnvybVl7mBmcI6XFXNobZs8hYSnYEwPK2Np5F1FvAzSajdDxYLZBlubPd+1ipEGY8e7PCcd5aRrNpoxSPcrs1v4WKyJWkoZtVfTp39Mkyr8T8gO6l9/QqaBr/jO6PlOpnwx9+XmcqGnOX2mgXVeYx18Yg=="
    },
    {
        "domain": "www.skillshare.com",
        "expirationDate": 1676754121,
        "hostOnly": true,
        "httpOnly": false,
        "name": "__pdst",
        "path": "/",
        "sameSite": "strict",
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "81261db22673486e9ec4f9d5114b4872"
    },
    {
        "domain": ".skillshare.com",
        "expirationDate": 1679086921,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__qca",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "P0-504436617-1645218121277"
    },
    {
        "domain": ".skillshare.com",
        "expirationDate": 1709619527,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__utmv",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "99704988.|1=visitor-type=user=1"
    },
    {
        "domain": ".skillshare.com",
        "expirationDate": 1662315527,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__utmz",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "99704988.1645218121.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)"
    },
    {
        "domain": ".skillshare.com",
        "expirationDate": 1678083529,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_clck",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "1xhc80v|1|ezj|0"
    },
    {
        "domain": ".skillshare.com",
        "expirationDate": 1646633931,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_clsk",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "1dn4elz|1646547531762|1|1|i.clarity.ms/collect"
    },
    {
        "domain": ".skillshare.com",
        "expirationDate": 1708423794,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "GA1.2.1620411679.1645218121"
    },
    {
        "domain": ".skillshare.com",
        "expirationDate": 1652994117,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_gcl_au",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "1.1.676753498.1645218118"
    },
    {
        "domain": ".skillshare.com",
        "expirationDate": 1677257206,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_pin_unauth",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "dWlkPVpUQmxOV05rTURJdE5qRm1aaTAwTVRNNUxUbGxaVGN0TlRkbU5tRXlNalV3WldWbQ"
    },
    {
        "domain": ".skillshare.com",
        "expirationDate": 1679404819,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_scid",
        "path": "/",
        "sameSite": "lax",
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "ae54b3dc-f0be-4428-bb47-7a0d0771d0f5"
    },
    {
        "domain": ".skillshare.com",
        "expirationDate": 1646633927,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_uetsid",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "43718b209d1511ecb8b727e1cf8505f8"
    },
    {
        "domain": ".skillshare.com",
        "expirationDate": 1962166732.610637,
        "hostOnly": false,
        "httpOnly": false,
        "name": "device_session_id",
        "path": "/",
        "sameSite": "lax",
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "556e1ea2-5ea9-4b1b-abec-3ec66b7b3e8a"
    },
    {
        "domain": "www.skillshare.com",
        "expirationDate": 1731618117.129135,
        "hostOnly": true,
        "httpOnly": false,
        "name": "first_landing",
        "path": "/",
        "sameSite": "lax",
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "utm_campaign%3D%26utm_source%3D%28direct%29%26utm_medium%3D%28none%29%26utm_term%3D%26referrer%3D%26referring_username%3D"
    },
    {
        "domain": ".www.skillshare.com",
        "expirationDate": 253402257600,
        "hostOnly": false,
        "httpOnly": false,
        "name": "G_ENABLED_IDPS",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "google"
    },
    {
        "domain": ".skillshare.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "IR_4650",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": true,
        "storeId": null,
        "value": "1646547527484%7C0%7C1646547527484%7C%7C"
    },
    {
        "domain": "www.skillshare.com",
        "hostOnly": true,
        "httpOnly": true,
        "name": "PHPSESSID",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": true,
        "storeId": null,
        "value": "65ff22cd9f018e455727fbb0c4e3da2a"
    },
    {
        "domain": "www.skillshare.com",
        "expirationDate": 1647810117.129102,
        "hostOnly": true,
        "httpOnly": false,
        "name": "show-like-copy",
        "path": "/",
        "sameSite": "lax",
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "1"
    },
    {
        "domain": ".skillshare.com",
        "expirationDate": 1654323532.610586,
        "hostOnly": false,
        "httpOnly": true,
        "name": "skillshare_user_",
        "path": "/",
        "sameSite": "lax",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "80f767f56a3abace7ae26fac0ed0f8507d32bd15a%3A4%3A%7Bi%3A0%3Bs%3A8%3A%2223841710%22%3Bi%3A1%3Bs%3A21%3A%22easyblog8%40outlook.com%22%3Bi%3A2%3Bi%3A7776000%3Bi%3A3%3Ba%3A5%3A%7Bs%3A8%3A%22username%22%3Bs%3A9%3A%22335428663%22%3Bs%3A10%3A%22login_time%22%3Bs%3A19%3A%222022-02-20%2010%3A10%3A23%22%3Bs%3A10%3A%22touch_time%22%3Bs%3A19%3A%222022-03-06%2006%3A18%3A51%22%3Bs%3A5%3A%22roles%22%3Bs%3A0%3A%22%22%3Bs%3A6%3A%22locale%22%3Bs%3A5%3A%22en-US%22%3B%7D%7D"
    },
    {
        "domain": ".skillshare.com",
        "expirationDate": 253402300799,
        "hostOnly": false,
        "httpOnly": false,
        "name": "sm_uuid",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "1645218691545"
    },
    {
        "domain": "www.skillshare.com",
        "expirationDate": 1647810117.129124,
        "hostOnly": true,
        "httpOnly": false,
        "name": "visitor_tracking",
        "path": "/",
        "sameSite": "lax",
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "utm_campaign%3D%26utm_source%3D%28direct%29%26utm_medium%3D%28none%29%26utm_term%3D%26referrer%3D%26referring_username%3D"
    }
]
"""

dl = skillshare(cookie=cookie)

# download by class URL:
dl.download_course_by_url('https://www.skillshare.com/classes/Art-Fundamentals-in-One-Hour/189505397')

# or by class ID:
# dl.download_course_by_class_id(189505397)
